apiVersion: apps/v1
---
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx:1.25
        name: webapp
        env:
        - name: ENVIRONMENT
          value: production
        - name: API_URL
          value: https://api.example.com
        ports:
        - containerPort: 80

---
apiVersion: v1
---
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
